export const CHARACTER_LIST = "CHARACTER/LIST";
export const CHARACTER_LIST_SUCCESS = "CHARACTER/LIST_SUCCESS";
export const CHARACTER_LIST_FAIL = "CHARACTER/LIST_FAIL";
export const CHARACTER_LIST_URL = "/characters";


export const CHARACTER_DETAIL = "CHARACTER/DETAIL";
export const CHARACTER_DETAIL_SUCCESS = "CHARACTER/DETAIL_SUCCESS";
export const CHARACTER_DETAIL_FAIL = "CHARACTER/DETAIL_FAIL";
export const CHARACTER_DETAIL_URL = "/characters/";

export const CHARACTER_OR_COMICS = "CHARACTER_OR/COMICS/DETAIL";
export const CHARACTER_OR_COMICS_SUCCESS = "CHARACTER_OR/COMICS/DETAIL_SUCCESS";
export const CHARACTER_OR_COMICS_FAIL = "CHARACTER_OR/COMICS/DETAIL_FAIL";
export const CHARACTER_OR_COMICS_URL = "/characters/";


