export const COMICS_LIST = "COMICS/LIST";
export const COMICS_LIST_SUCCESS = "COMICS/LIST_SUCCESS";
export const COMICS_LIST_FAIL = "COMICS/LIST_FAIL";
export const COMICS_LIST_URL = "/comics";

export const COMICS_DETAIL = "COMICS/DETAIL";
export const COMICS_DETAIL_SUCCESS = "COMICS/DETAIL_SUCCESS";
export const COMICS_DETAIL_FAIL = "COMICS/DETAIL_FAIL";
export const COMICS_DETAIL_URL = "/comics/";

export const COMICS_OR_CHARACTER = "COMICS/CHARACTER";
export const COMICS_OR_CHARACTER_SUCCESS = "COMICS/CHARACTER_SUCCESS";
export const COMICS_OR_CHARACTER_FAIL = "COMICS/CHARACTER_FAIL";
export const COMICS_OR_CHARACTER_URL = "/comics/";

export const COMICS_OR_CREATORS = "COMICS/OR_CREATORS";
export const COMICS_OR_CREATORS_SUCCESS = "COMICS/OR_CREATORS_SUCCESS";
export const COMICS_OR_CREATORS_FAIL = "COMICS/OR_CREATORS_FAIL";
export const COMICS_OR_CREATORS_URL = "/comics/";
